a list:
  - 1
  - 42
  - 3.141
  - 1337
  - help
  - €
pi_pins:
  rot_dir_pin: 5
  rot_step_pin: 6
  rot_en_pin: 21
  lin_dir_pin: 24
  lin_step_pin: 25
  lin_en_pin: 7
  outer_limit_pin: 22
  inner_limit_pin: 18
  rotation_limit_pin: 17
